export type Person = {
	bio?: string;
	biography?: string;
	birthdate?: string;
	deathdate?: string;
	isdeceased?: string;
	email?: string;
	facebook?: string;
	fid?: string;
	gender: string;
	hobbies?: string;
	id: string;
	instagram?: string;
	mid?: string;
	name?: string;
	phone?: string;
	pids?: string[];
	portrait?: string;
	profession?: string;
	datestring: string;
};
