import NavBar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Family Tree",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='flex flex-col min-h-screen'>
				<header className=' sticky z-50 top-0'>
					<NavBar />
				</header>
				<main className='grow'>{children}</main>
			</body>
		</html>
	);
}
