import NavBar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { MongoClient } from "mongodb";
// import { connectDB } from "@/scripts/database";
import { useEffect } from "react";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Family Tree",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			{/* <body className={inter.className}>{children}</body> */}
			<body className='flex flex-col min-h-screen'>
				<header>
					<NavBar />
				</header>
				<main>{children}</main>
			</body>
		</html>
	);
}
